### ISSUE TITLE
ConnectionInitializationException is thrown on bad credentials

### ISSUE THREAD

**Issue by smancke** [osiam/connector4java#117]
When I use the retrieveAccessToken with the ResourceOwnerPasswordCredentials Grant type,
then I can't see, if the credentials are wrong, or if I have a technical error (e.g. osiam server not found). Always ConnectionInitializationException is thrown. I would expect something like a LoginException.

**Comment by dacrome** [comment]
When the `auth-server` [returns `400/Bad Request` a `ConnectionInitializationException` is thrown](https://github.com/osiam/connector4java/blob/master/src/main/java/org/osiam/client/AuthService.java#L296). I expected something like `BadRequestException`. But I also expected a `401/Unauthorized` from the `auth-server`s `/oauth/token` (internal spring security) endpoint if the credentials are wrong. The only way to find out if the credentials are wrong is to check the response body against `Bad Credentials`. How should we handle this?

**Comment by tkrille** [comment]
> But I also expected a 401/Unauthorized from the auth-servers /oauth/token (internal spring security) endpoint if the credentials are wrong.

What does the spec say? Did we change something about this endpoint or is it still vanilla Spring Security OAuth?

> The only way to find out if the credentials are wrong is to check the response body against `Bad Credentials`. How should we handle this?

Why not checking the response body? At least we definitely know what context we're in at this point. We should throw something like a `BadCredentialsException` then.

**Comment by dacrome** [comment]
/oauth/token is provided by Spring Security OAuth so we should just check the body against 'Bad Credentials' if the response code is 400/Bad Request and throwing a BadCredentialsException
