### ISSUE TITLE
increase connection timeout

### ISSUE THREAD

**Issue by timopick** [osiam/connector4java#120]
increase CONNECT_TIMEOUT and READ_TIMEOUT parameters

files:
src/main/java/org/osiam/client/AbstractOsiamService.java
src/main/java/org/osiam/client/AuthService.java

<pre>
-    private static final int CONNECT_TIMEOUT = 2500;
-    private static final int READ_TIMEOUT = 5000;
+    private static final int CONNECT_TIMEOUT = 250000;
+    private static final int READ_TIMEOUT = 500000;
</pre>

**Comment by dacrome** [comment]
The timeouts should be configurable. The increased values are way to high for a standard environment.
