### ISSUE TITLE
Handling of trailing '/' in URLs

### ISSUE THREAD

**Issue by tkrille** [osiam/connector4java#141]
A trialing forward slash in the endpoint URL leads to some incorrect looking URLs. For example, this is a URL generated by `OsiamConnector#getAuthorizationUri`, if the auth-server endpoint is set to `http://localhost:8080/osiam-server/`:

    http://localhost:8080/osiam-server//oauth/authorize?client_id=...

Note the double forward slashes in `/osiam-server//oauth/authorize`. Note also, that this is not causing erroneous behavior in any following-up component like Jersey client or the actual browser that follows these URLs.

**Comment by wallner** [comment]
This issue is no longer valid since we moved to Jersey. I am in the process to come up with a PR that proves it.
