### ISSUE TITLE
Connector only allows only one connection per client

### ISSUE THREAD

**Issue by tpick** [osiam/connector4java#144]
The connector seems to reuse the same connection to the OSIAM auth- and resource server. This may lead to a performance bottleneck when multiple threads from the client application try to interact with Osiam. All other threads in the client have to wait until the connector is freed.

**Comment by tkrille** [comment]
This seems to be an issue with the Apache HTTP client that only allows 2 simultaneous connection to the same host (this is actually specified by the HTTP or some other spec). Fortunately, this can be easily configured, for example like this guy does it: http://www.theotherian.com/2013/08/jersey-client-2.0-httpclient-timeouts-max-connections.html

**Comment by tkrille** [comment]
This is now configurable. See #145.
