### ISSUE TITLE
POST requests return HTTP 400 in Resin 4 deployments

### ISSUE THREAD

**Issue by xaviarias** [osiam/connector4java#179]
We are testing the OSIAM connector4java (v1.7) against an OSIAM Auth server mock deployed in a Resin 4 container (Mac OS X and CentOS), and we are getting a server error likely caused by the Jersey client usage by the OSIAM connector.

The error occurs because Resin doesn't allow POST requests without a `Content-length` header. To reproduce, deploy the auth server in Resin, and when invoking: 

`osiamConnector.revokeAccessToken(accessToken);`

The server returns a HTTP 400 Bad request response:
<html>
<body>
<h1>POST requires content-length</h1>
<pre>POST requires content-length</pre>
<p /><hr />
<small>
Resin/4.0.46
Server: 'app-0'
</small>
</body></html>

Looking at the connector code, there are some methods ending Jersey client requests with ` .post(null);`:

https://github.com/osiam/connector4java/blob/master/src/main/java/org/osiam/client/AuthService.java

This could be solved by merely changing `null` to an empty string. This would force Jersey client to set the required header with a zero value.

**Comment by tkrille** [comment]
Hi @xaviarias,

thanks for your finding! We will fix this with the next release. I'm curious about what you're doing with OSIAM and especially with the connector and the mentioned mock. Would you like to tell me more about it?

**Comment by xaviarias** [comment]
Hi @tkrille,

Thank you for the quick response. We are evaluating OSIAM as the identity and access management solution for our company.

We are using the Vagrant image and so far the results are very positive, but I think is hasn't the latest OSIAM version and therefore not fully functional (i.e. UI roles support).

Do you have a prevision for the v3.0 release? 

Thanks!

**Comment by dacrome** [comment]
Hi @xaviarias,

nice to hear about the positive results of your evaluation.

> We are using the Vagrant image and so far the results are very positive, but I think is hasn't the latest OSIAM version and therefore not fully functional (i.e. UI roles support).

> Do you have a prevision for the v3.0 release? 

The vagrant vm currently just supports released versions of the OSIAM components. But you have two options to use the latest snapshots:
* The easiest option is to use the [OSIAM docker image](https://github.com/osiam/docker-image):
  * `$ docker pull osiamorg/osiam`
  * You can also [clone](https://github.com/osiam/docker-image.git) or download the docker repo and build the docker image with `./build`
  * `$ docker run -i -t -p 8080:8080 -p 5432:5432 -p 10110:10110 osiamorg/osiam`
* If the docker image is not an option, you can update the vagrant vm manually by cloning [OSIAM](https://github.com/osiam/osiam) and copy the sources to specific folders as root (`$ sudo -i` as vagrant user):
  * `$ git clone https://github.com/osiam/osiam.git`
  * `$ cd osiam && mvn clean package`
  * `$ cp -r src/main/deploy/* /etc/osiam`
  * You need to overwrite the properties file with my created gist:
  * `$ wget https://gist.githubusercontent.com/dacrome/62be50018418d90b5090/raw/ec7215ae62ad6c4ccc389afa72aeb9b72a6c8dde/osiam.properties -O /etc/osiam/osiam.properties`
  * `$ cp target/osiam.war /var/lib/tomcat7/webapps`
  * If you also like to run the latest snapshots of the addons, don't hesitate to ask, I will post how you can update them.

**Comment by dacrome** [comment]
Actually it's quite easy to update also the addons:
* addon-self-administration
  * `$ wget https://maven-repo.evolvis.org/snapshots/org/osiam/addon-self-administration/2.0-SNAPSHOT/addon-self-administration-2.0-20151031.195622-15.war -O /var/lib/tomcat7/webapps/addon-self-administration.war`
* addon-administration
  * `$ wget https://maven-repo.evolvis.org/snapshots/org/osiam/addon-administration/2.0-SNAPSHOT/addon-administration-2.0-20151031.195614-13.war -O /var/lib/tomcat7/webapps/addon-administration.war`
* `$ service tomcat7 restart`

Again, you can also clone the sources and build them by your own.

**Comment by tkrille** [comment]
@xaviarias It's probably the best if you use the Docker image. It always contains the most recent stuff from the master branches. Have fun with OSIAM and if you have any questions, don't hesitate to open a new issue and ask them.

**Comment by xaviarias** [comment]
Thanks @dacrome and @tkrille  for your inputs, we have switched from Vagrant to Docker image and it works perfectly well.

**Comment by tkrille** [comment]
@xaviarias I've re-opened this, because the original issue that you've reported, is still open :)

**Comment by tkrille** [comment]
This should be fixed in the current 1.8-SNAPSHOT. Can you confirm this @xaviarias?

**Comment by xaviarias** [comment]
Looking at the code I would say yes, but we don't have access to the snapshots repository to test the patch.

**Comment by tkrille** [comment]
@xaviarias Good to hear that :) And thanks again for your finding.
