### ISSUE TITLE
Deploy releases to Bintray with CircleCI

### ISSUE THREAD

**Issue by dacrome** [osiam/connector4java#215]
@tkrille already [lists the steps](https://github.com/osiam/osiam/issues/194#issuecomment-200392152) which are need to be done to deploy releases to Bintray with CircleCI. The steps need to be adapt to the connector4java releases.

**Comment by tkrille** [comment]
With the difference, that the connector must end up on the central.

**Comment by tkrille** [comment]
And ending up on the central is the only requirement, no need for putting it in the generic _osiam-downloads_ repo.

**Comment by tkrille** [comment]
@dacrome I would do this now. Is that okay with you?

**Comment by dacrome** [comment]
It's yours!

**Comment by tkrille** [comment]
Here you are.
